In [48]:
import numpy as np

In [49]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [50]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
np.linspace(0, 5 , 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [53]:
# identity
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.rand(5)

array([0.8494769 , 0.71864242, 0.62929883, 0.61479414, 0.4135941 ])

In [56]:
np.random.rand(5,5)

array([[0.4006039 , 0.99366276, 0.68821088, 0.28996246, 0.77774461],
       [0.66819992, 0.88118258, 0.99521377, 0.76714615, 0.62410873],
       [0.12662714, 0.57488578, 0.54181836, 0.85777335, 0.34558357],
       [0.01618968, 0.84467217, 0.84603359, 0.19233239, 0.4818423 ],
       [0.29489316, 0.7853988 , 0.07195477, 0.46336   , 0.14867762]])

In [ ]:
np.random.randn(2,4)

In [55]:
np.random.randint(1,100, 5)

array([34, 97, 33, 32, 77])

In [57]:
arr = np.arange(25)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [59]:
ranarr = np.random.randint(0,50,10)

In [60]:
ranarr

array([ 3, 25, 48, 28, 25, 24,  8, 22, 11, 20])

In [ ]:
arr.reshape(5, 5)

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.argmin()

In [ ]:
arr.shape
#shows 1-dimension

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr.shape

In [ ]:
arr.dtype

In [ ]:
# can skip the random. if we just import the randint function
from numpy.random import randint

In [ ]:
randint(2,10)

Indexing and Selection

In [64]:
arr = np.arange(0,11)

In [65]:
arr[8]

8

In [63]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[5:10]

In [ ]:
arr[:6]

In [ ]:
arr[4:]

In [ ]:
arr[0:5] = 100

In [ ]:
arr

In [ ]:
arr = np.arange(0,11)

In [ ]:
slice_of_arr = arr[0:6]

In [ ]:
slice_of_arr

In [ ]:
# slice modifies the value arr is looking at
slice_of_arr[:] = 99

In [ ]:
arr

In [ ]:
# to create an actual copy
arr_copy = arr.copy()

In [ ]:
arr_copy

In [ ]:
arr_copy[:] = 100

In [ ]:
arr

In [ ]:
arr_copy

In [1]:
import numpy as np

In [3]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
arr_2d[0][0]

5

In [8]:
arr_2d[1][1]

25

In [11]:
# can use , instead of ][
arr_2d[2,1]

40

In [12]:
# up to row 2, from column 1
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
arr_2d[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [19]:
arr = np.arange(1,11)

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
bool_arr = arr > 5

In [23]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [24]:
# equivalent to bool_arr
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [25]:
arr_2d = np.arange(50).reshape(5,10)

In [26]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [32]:
arr_2d[3:5,8:10]

array([[38, 39],
       [48, 49]])

# Numpy Operations

In [33]:
arr = np.arange(0,11)

In [34]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [36]:
# trying to divide by 0
arr / arr

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [37]:
# trying to divide by 0
1 / arr

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [38]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [40]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [41]:
# equivalent to method 
np.max(arr)

10

In [42]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [43]:
np.log(arr)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [44]:
np.log

<ufunc 'log'>